"""m3a_foundation_alignment

Revision ID: 2105faf7bef7
Revises: 2fc5f4775fef
Create Date: 2026-09-14 00:54:18.883288

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2105faf7bef7'
down_revision: str | None = '2fc5f4775fef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acquisition_mechanism', sa.String(length=24), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jurisdiction_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('licence_kind', sa.String(length=16), nullable=False),
    sa.Column('licence_state', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("acquisition_mechanism in ('portal_api', 'portal_scrape', 'direct_api', 'manual', 'inbound_email')", name='ck_connector_acquisition_mechanism'),
    sa.CheckConstraint("licence_kind in ('none_required', 'commercial', 'licensed')", name='ck_connector_licence_kind'),
    sa.CheckConstraint("licence_state in ('not_required', 'pending', 'active', 'suspended', 'expired')", name='ck_connector_licence_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_connector_definition_slug')
    )
    op.create_table('connector_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_actor_user_id', sa.UUID(), nullable=True),
    sa.Column('credential_ref', sa.String(length=200), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('readiness_state', sa.String(length=16), nullable=False),
    sa.Column('health_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_detail', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("readiness_state in ('unconfigured', 'ready', 'degraded', 'error', 'kill_switch')", name='ck_connector_instance_readiness_state'),
    sa.ForeignKeyConstraint(['consent_actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_id'], ['connector_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'definition_id', name='uq_connector_instance_workspace_definition')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_kind', sa.String(length=32), nullable=False),
    sa.Column('schedule_cron', sa.String(length=80), nullable=False),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_kind in ('brief_reevaluation', 'source_health_check', 'intake_processing', 'report_release')", name='ck_scheduled_job_kind'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('canonical_email', sa.String(length=320), nullable=False),
    sa.Column('alias_email', sa.String(length=320), nullable=False),
    sa.Column('display_names_seen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_label', sa.String(length=200), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence in ('verified', 'high', 'medium', 'low')", name='ck_sender_alias_confidence'),
    sa.CheckConstraint("review_state in ('pending', 'confirmed', 'rejected')", name='ck_sender_alias_review_state'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'alias_email', name='uq_sender_alias_workspace_email')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('run_state', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=400), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_state in ('running', 'completed', 'failed', 'skipped')", name='ck_job_run_state'),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_job_started', 'job_runs', ['job_id', 'started_at'], unique=False)
    op.create_table('source_readiness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector_instance_id', sa.UUID(), nullable=False),
    sa.Column('readiness_state', sa.String(length=16), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deviation_reason', sa.String(length=400), nullable=True),
    sa.Column('status_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("readiness_state in ('initialising', 'ready', 'degraded', 'offline', 'kill_switch')", name='ck_source_readiness_state'),
    sa.ForeignKeyConstraint(['connector_instance_id'], ['connector_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'connector_instance_id', name='uq_source_readiness_workspace_connector')
    )
    op.create_table('discovery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('claim', sa.String(length=200), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel in ('portal', 'email', 'manual', 'agent_referral', 'direct')", name='ck_discovery_channel'),
    sa.CheckConstraint("event_type in ('first_discovery', 'channel_event')", name='ck_discovery_event_type'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovery_workspace_property', 'discovery_events', ['workspace_id', 'property_id'], unique=False)
    op.create_index('uq_discovery_first_per_workspace_property', 'discovery_events', ['workspace_id', 'property_id'], unique=True, postgresql_where=sa.text("event_type = 'first_discovery'"))
    op.create_table('enrichment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=False),
    sa.Column('provenance', sa.String(length=400), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freshness_days', sa.Integer(), nullable=True),
    sa.Column('value_state', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence in ('stated', 'derived', 'estimated', 'unknown')", name='ck_enrichment_confidence'),
    sa.CheckConstraint("kind in ('planning', 'constraint_layer', 'notable_place', 'travel')", name='ck_enrichment_kind'),
    sa.CheckConstraint("value_state in ('known', 'unknown', 'not_applicable', 'conflict')", name='ck_enrichment_value_state'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'kind', 'source_label', name='uq_enrichment_property_kind_source')
    )
    op.create_index('ix_enrichment_property', 'enrichment_records', ['property_id'], unique=False)
    op.create_table('intake_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_property_id', sa.UUID(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('first_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel in ('portal', 'email', 'manual', 'agent_referral', 'direct')", name='ck_intake_event_channel'),
    sa.CheckConstraint("state in ('pending', 'processing', 'completed', 'failed', 'duplicate')", name='ck_intake_event_state'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_intake_event_workspace_key')
    )
    op.create_index('ix_intake_events_workspace_journey', 'intake_events', ['workspace_id', 'journey_id'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('brief_version_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('release_state', sa.String(length=16), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('preview', 'on_demand', 'production')", name='ck_report_run_kind'),
    sa.CheckConstraint("release_state in ('pending', 'generating', 'ready', 'failed', 'released')", name='ck_report_run_release_state'),
    sa.ForeignKeyConstraint(['brief_version_id'], ['brief_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_report_run_workspace_key')
    )
    op.create_index('ix_report_runs_workspace_journey', 'report_runs', ['workspace_id', 'journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_runs_workspace_journey', table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index('ix_intake_events_workspace_journey', table_name='intake_events')
    op.drop_table('intake_events')
    op.drop_index('ix_enrichment_property', table_name='enrichment_records')
    op.drop_table('enrichment_records')
    op.drop_index('uq_discovery_first_per_workspace_property', table_name='discovery_events', postgresql_where=sa.text("event_type = 'first_discovery'"))
    op.drop_index('ix_discovery_workspace_property', table_name='discovery_events')
    op.drop_table('discovery_events')
    op.drop_table('source_readiness')
    op.drop_index('ix_job_runs_job_started', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('sender_aliases')
    op.drop_table('scheduled_jobs')
    op.drop_table('connector_instances')
    op.drop_table('connector_definitions')
    # ### end Alembic commands ###
