"""m3 property workspace evidence matching

Revision ID: 2fc5f4775fef
Revises: 4bb12e1e9183
Create Date: 2026-09-04 09:10:22.353481

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fc5f4775fef'
down_revision: str | None = '4bb12e1e9183'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('legacy_ref', sa.String(length=40), nullable=True),
    sa.Column('address_line', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('suburb', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=3), nullable=False),
    sa.Column('postcode', sa.String(length=4), nullable=True),
    sa.Column('normalised_address', sa.String(length=320), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_attribution', sa.String(length=200), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'normalised_address', name='uq_property_workspace_address')
    )
    op.create_index('ix_properties_workspace_journey', 'properties', ['workspace_id', 'journey_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_journey_created', 'activity_events', ['journey_id', 'created_at'], unique=False)
    op.create_table('buyer_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('buyer_state', sa.String(length=24), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_changed_by', sa.UUID(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("buyer_state in ('reviewing', 'shortlisted', 'inspection_considered', 'inspected', 'due_diligence', 'offer_preparation', 'offer_submitted', 'under_contract', 'settled', 'rejected', 'archived')", name='ck_buyer_state'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'property_id', name='uq_buyer_property_journey')
    )
    op.create_index('ix_buyer_properties_workspace_journey', 'buyer_properties', ['workspace_id', 'journey_id'], unique=False)
    op.create_table('gate_waivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('criterion', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waivers_property', 'gate_waivers', ['property_id'], unique=False)
    op.create_table('listing_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=False),
    sa.Column('market_state', sa.String(length=16), nullable=False),
    sa.Column('price_kind', sa.String(length=32), nullable=False),
    sa.Column('raw_price', sa.String(length=120), nullable=False),
    sa.Column('lower_minor', sa.Integer(), nullable=True),
    sa.Column('upper_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_source', sa.String(length=120), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("market_state in ('active', 'under_offer', 'withdrawn', 'sold', 'unknown')", name='ck_campaign_market_state'),
    sa.CheckConstraint("price_kind in ('exact', 'range', 'from', 'offers_over', 'auction', 'contact_agent', 'expressions_of_interest', 'conflicting')", name='ck_campaign_price_kind'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_property', 'listing_campaigns', ['property_id'], unique=False)
    op.create_table('match_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('brief_version_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('fit_pct', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict in ('pass','fail','unknown')", name='ck_evaluation_verdict'),
    sa.ForeignKeyConstraint(['brief_version_id'], ['brief_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'brief_version_id', name='uq_evaluation_property_version')
    )
    op.create_index('ix_evaluations_journey_version', 'match_evaluations', ['journey_id', 'brief_version_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("source_kind in ('original_source', 'partial', 'manual', 'conflict')", name='ck_observation_source_kind'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_property', 'observations', ['property_id'], unique=False)
    op.create_table('property_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_property', 'property_notes', ['property_id'], unique=False)
    op.create_table('property_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_property', 'property_tasks', ['property_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('value_state', sa.String(length=16), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_text', sa.String(length=80), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('conflict_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key in ('beds', 'baths', 'cars', 'land_sqm', 'floor_sqm', 'property_type', 'detached', 'condition', 'location_tier')", name='ck_fact_key'),
    sa.CheckConstraint("value_state in ('known', 'unknown', 'not_applicable', 'conflict')", name='ck_fact_value_state'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'key', name='uq_fact_property_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facts')
    op.drop_index('ix_tasks_property', table_name='property_tasks')
    op.drop_table('property_tasks')
    op.drop_index('ix_notes_property', table_name='property_notes')
    op.drop_table('property_notes')
    op.drop_index('ix_observations_property', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_evaluations_journey_version', table_name='match_evaluations')
    op.drop_table('match_evaluations')
    op.drop_index('ix_campaigns_property', table_name='listing_campaigns')
    op.drop_table('listing_campaigns')
    op.drop_index('ix_waivers_property', table_name='gate_waivers')
    op.drop_table('gate_waivers')
    op.drop_index('ix_buyer_properties_workspace_journey', table_name='buyer_properties')
    op.drop_table('buyer_properties')
    op.drop_index('ix_activity_journey_created', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_properties_workspace_journey', table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
